import { createFileRoute, Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useCompany } from '@/lib/company';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CalendarCheck, Clock, UserRound, Wallet } from 'lucide-react';
import { brl } from '@/lib/format';
export const Route=createFileRoute('/_authenticated/app/operations')({component:Operations});
function Operations(){const {activeCompany}=useCompany(); const id=activeCompany?.id; const {data:rows=[]}=useQuery({queryKey:['operations-today',id],enabled:!!id,queryFn:async()=>{const a=new Date();a.setHours(0,0,0,0);const b=new Date(a);b.setDate(b.getDate()+1);const {data,error}=await supabase.from('appointments').select('id,starts_at,ends_at,status,total_cents,customer:customers(name),staff:staff(name)').eq('company_id',id!).gte('starts_at',a.toISOString()).lt('starts_at',b.toISOString()).order('starts_at');if(error)throw error;return data??[]}});return <div className="space-y-6"><div><p className="text-xs uppercase tracking-[.18em] text-muted-foreground">Operação do dia</p><h1 className="text-2xl font-semibold">Central de Atendimento</h1><p className="text-muted-foreground">Agenda, cliente e fechamento do atendimento em um único fluxo.</p></div><div className="grid gap-3 md:grid-cols-3"><Card><CardContent className="p-5"><CalendarCheck className="h-4 w-4 mb-3"/><p className="text-2xl font-semibold">{rows.length}</p><p className="text-sm text-muted-foreground">atendimentos hoje</p></CardContent></Card><Card><CardContent className="p-5"><Clock className="h-4 w-4 mb-3"/><p className="text-2xl font-semibold">{rows.filter((x:any)=>!['completed','cancelled','no_show'].includes(x.status)).length}</p><p className="text-sm text-muted-foreground">em andamento ou aguardando</p></CardContent></Card><Card><CardContent className="p-5"><Wallet className="h-4 w-4 mb-3"/><p className="text-2xl font-semibold">{brl(rows.reduce((n:number,x:any)=>n+(x.total_cents||0),0))}</p><p className="text-sm text-muted-foreground">valor previsto</p></CardContent></Card></div><Card><CardHeader><CardTitle>Fila operacional</CardTitle></CardHeader><CardContent className="space-y-3">{rows.map((x:any)=><div key={x.id} className="flex flex-wrap items-center gap-3 rounded-2xl border p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-muted"><UserRound className="h-4 w-4"/></div><div className="min-w-40 flex-1"><p className="font-medium">{x.customer?.name||'Cliente'}</p><p className="text-xs text-muted-foreground">{new Date(x.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · {x.staff?.name||'Sem profissional'}</p></div><Badge variant="secondary">{x.status}</Badge><strong>{brl(x.total_cents||0)}</strong><Button asChild size="sm"><Link to="/app/payments">Fechar atendimento</Link></Button></div>)}{!rows.length&&<p className="py-8 text-center text-muted-foreground">Nenhum atendimento para hoje.</p>}</CardContent></Card></div>}
