/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmarTokenRouteImport } from './routes/confirmar.$token'
import { Route as AvaliarTokenRouteImport } from './routes/avaliar.$token'
import { Route as AvaliacaoTokenRouteImport } from './routes/avaliacao.$token'
import { Route as AuthenticatedNoAccessRouteImport } from './routes/_authenticated/no-access'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as BSlugIndexRouteImport } from './routes/b.$slug.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as BSlugMinhaContaRouteImport } from './routes/b.$slug.minha-conta'
import { Route as BSlugEntrarRouteImport } from './routes/b.$slug.entrar'
import { Route as ApiPublicStaffRouteImport } from './routes/api/public/staff'
import { Route as ApiPublicReviewRouteImport } from './routes/api/public/review'
import { Route as ApiPublicDepositRouteImport } from './routes/api/public/deposit'
import { Route as ApiPublicCouponRouteImport } from './routes/api/public/coupon'
import { Route as ApiPublicConfirmRouteImport } from './routes/api/public/confirm'
import { Route as ApiPublicCompanyReviewRouteImport } from './routes/api/public/company-review'
import { Route as ApiPublicBookRouteImport } from './routes/api/public/book'
import { Route as ApiPublicAnamnesisRouteImport } from './routes/api/public/anamnesis'
import { Route as AuthenticatedAppWhatsappRouteImport } from './routes/_authenticated/app/whatsapp'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app/users'
import { Route as AuthenticatedAppStaffRouteImport } from './routes/_authenticated/app/staff'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app/services'
import { Route as AuthenticatedAppSalesRouteImport } from './routes/_authenticated/app/sales'
import { Route as AuthenticatedAppRewardsRouteImport } from './routes/_authenticated/app/rewards'
import { Route as AuthenticatedAppReviewsRouteImport } from './routes/_authenticated/app/reviews'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app/reports'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app/products'
import { Route as AuthenticatedAppProceduresRouteImport } from './routes/_authenticated/app/procedures'
import { Route as AuthenticatedAppPortalRouteImport } from './routes/_authenticated/app/portal'
import { Route as AuthenticatedAppPlansRouteImport } from './routes/_authenticated/app/plans'
import { Route as AuthenticatedAppPaymentsRouteImport } from './routes/_authenticated/app/payments'
import { Route as AuthenticatedAppLoyaltyRouteImport } from './routes/_authenticated/app/loyalty'
import { Route as AuthenticatedAppLinkRouteImport } from './routes/_authenticated/app/link'
import { Route as AuthenticatedAppGalleryRouteImport } from './routes/_authenticated/app/gallery'
import { Route as AuthenticatedAppFinancesRouteImport } from './routes/_authenticated/app/finances'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app/customers'
import { Route as AuthenticatedAppCouponsRouteImport } from './routes/_authenticated/app/coupons'
import { Route as AuthenticatedAppConfirmationsRouteImport } from './routes/_authenticated/app/confirmations'
import { Route as AuthenticatedAppCommissionsRouteImport } from './routes/_authenticated/app/commissions'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app/campaigns'
import { Route as AuthenticatedAppBlocksRouteImport } from './routes/_authenticated/app/blocks'
import { Route as AuthenticatedAppBirthdaysRouteImport } from './routes/_authenticated/app/birthdays'
import { Route as AuthenticatedAppAttendanceRouteImport } from './routes/_authenticated/app/attendance'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app/ai'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app/agenda'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminNichesRouteImport } from './routes/_authenticated/admin/niches'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'
import { Route as BSlugAvaliarAppointmentIdRouteImport } from './routes/b.$slug.avaliar.$appointmentId'
import { Route as ApiPublicHooksReviewInvitesRouteImport } from './routes/api/public/hooks/review-invites'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'
import { Route as ApiPublicHooksConfirmationsRouteImport } from './routes/api/public/hooks/confirmations'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarTokenRoute = ConfirmarTokenRouteImport.update({
  id: '/confirmar/$token',
  path: '/confirmar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarTokenRoute = AvaliarTokenRouteImport.update({
  id: '/avaliar/$token',
  path: '/avaliar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoTokenRoute = AvaliacaoTokenRouteImport.update({
  id: '/avaliacao/$token',
  path: '/avaliacao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNoAccessRoute = AuthenticatedNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BSlugIndexRoute = BSlugIndexRouteImport.update({
  id: '/b/$slug/',
  path: '/b/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const BSlugMinhaContaRoute = BSlugMinhaContaRouteImport.update({
  id: '/b/$slug/minha-conta',
  path: '/b/$slug/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugEntrarRoute = BSlugEntrarRouteImport.update({
  id: '/b/$slug/entrar',
  path: '/b/$slug/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStaffRoute = ApiPublicStaffRouteImport.update({
  id: '/api/public/staff',
  path: '/api/public/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReviewRoute = ApiPublicReviewRouteImport.update({
  id: '/api/public/review',
  path: '/api/public/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDepositRoute = ApiPublicDepositRouteImport.update({
  id: '/api/public/deposit',
  path: '/api/public/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCouponRoute = ApiPublicCouponRouteImport.update({
  id: '/api/public/coupon',
  path: '/api/public/coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfirmRoute = ApiPublicConfirmRouteImport.update({
  id: '/api/public/confirm',
  path: '/api/public/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCompanyReviewRoute = ApiPublicCompanyReviewRouteImport.update({
  id: '/api/public/company-review',
  path: '/api/public/company-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookRoute = ApiPublicBookRouteImport.update({
  id: '/api/public/book',
  path: '/api/public/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnamnesisRoute = ApiPublicAnamnesisRouteImport.update({
  id: '/api/public/anamnesis',
  path: '/api/public/anamnesis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWhatsappRoute =
  AuthenticatedAppWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppStaffRoute = AuthenticatedAppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSalesRoute = AuthenticatedAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRewardsRoute = AuthenticatedAppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReviewsRoute = AuthenticatedAppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProceduresRoute =
  AuthenticatedAppProceduresRouteImport.update({
    id: '/procedures',
    path: '/procedures',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPortalRoute = AuthenticatedAppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPlansRoute = AuthenticatedAppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPaymentsRoute =
  AuthenticatedAppPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLoyaltyRoute = AuthenticatedAppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppLinkRoute = AuthenticatedAppLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppGalleryRoute = AuthenticatedAppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppFinancesRoute =
  AuthenticatedAppFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCouponsRoute = AuthenticatedAppCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppConfirmationsRoute =
  AuthenticatedAppConfirmationsRouteImport.update({
    id: '/confirmations',
    path: '/confirmations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCommissionsRoute =
  AuthenticatedAppCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBlocksRoute = AuthenticatedAppBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppBirthdaysRoute =
  AuthenticatedAppBirthdaysRouteImport.update({
    id: '/birthdays',
    path: '/birthdays',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAttendanceRoute =
  AuthenticatedAppAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNichesRoute =
  AuthenticatedAdminNichesRouteImport.update({
    id: '/niches',
    path: '/niches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const BSlugAvaliarAppointmentIdRoute =
  BSlugAvaliarAppointmentIdRouteImport.update({
    id: '/b/$slug/avaliar/$appointmentId',
    path: '/b/$slug/avaliar/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReviewInvitesRoute =
  ApiPublicHooksReviewInvitesRouteImport.update({
    id: '/api/public/hooks/review-invites',
    path: '/api/public/hooks/review-invites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksConfirmationsRoute =
  ApiPublicHooksConfirmationsRouteImport.update({
    id: '/api/public/hooks/confirmations',
    path: '/api/public/hooks/confirmations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/no-access': typeof AuthenticatedNoAccessRoute
  '/avaliacao/$token': typeof AvaliacaoTokenRoute
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/niches': typeof AuthenticatedAdminNichesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/app/birthdays': typeof AuthenticatedAppBirthdaysRoute
  '/app/blocks': typeof AuthenticatedAppBlocksRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/commissions': typeof AuthenticatedAppCommissionsRoute
  '/app/confirmations': typeof AuthenticatedAppConfirmationsRoute
  '/app/coupons': typeof AuthenticatedAppCouponsRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/finances': typeof AuthenticatedAppFinancesRoute
  '/app/gallery': typeof AuthenticatedAppGalleryRoute
  '/app/link': typeof AuthenticatedAppLinkRoute
  '/app/loyalty': typeof AuthenticatedAppLoyaltyRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/plans': typeof AuthenticatedAppPlansRoute
  '/app/portal': typeof AuthenticatedAppPortalRoute
  '/app/procedures': typeof AuthenticatedAppProceduresRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/sales': typeof AuthenticatedAppSalesRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/staff': typeof AuthenticatedAppStaffRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/public/anamnesis': typeof ApiPublicAnamnesisRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/api/public/company-review': typeof ApiPublicCompanyReviewRoute
  '/api/public/confirm': typeof ApiPublicConfirmRoute
  '/api/public/coupon': typeof ApiPublicCouponRoute
  '/api/public/deposit': typeof ApiPublicDepositRoute
  '/api/public/review': typeof ApiPublicReviewRoute
  '/api/public/staff': typeof ApiPublicStaffRoute
  '/b/$slug/entrar': typeof BSlugEntrarRoute
  '/b/$slug/minha-conta': typeof BSlugMinhaContaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/api/public/hooks/confirmations': typeof ApiPublicHooksConfirmationsRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/hooks/review-invites': typeof ApiPublicHooksReviewInvitesRoute
  '/b/$slug/avaliar/$appointmentId': typeof BSlugAvaliarAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/no-access': typeof AuthenticatedNoAccessRoute
  '/avaliacao/$token': typeof AvaliacaoTokenRoute
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/niches': typeof AuthenticatedAdminNichesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/app/birthdays': typeof AuthenticatedAppBirthdaysRoute
  '/app/blocks': typeof AuthenticatedAppBlocksRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/commissions': typeof AuthenticatedAppCommissionsRoute
  '/app/confirmations': typeof AuthenticatedAppConfirmationsRoute
  '/app/coupons': typeof AuthenticatedAppCouponsRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/finances': typeof AuthenticatedAppFinancesRoute
  '/app/gallery': typeof AuthenticatedAppGalleryRoute
  '/app/link': typeof AuthenticatedAppLinkRoute
  '/app/loyalty': typeof AuthenticatedAppLoyaltyRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/plans': typeof AuthenticatedAppPlansRoute
  '/app/portal': typeof AuthenticatedAppPortalRoute
  '/app/procedures': typeof AuthenticatedAppProceduresRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/sales': typeof AuthenticatedAppSalesRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/staff': typeof AuthenticatedAppStaffRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/public/anamnesis': typeof ApiPublicAnamnesisRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/api/public/company-review': typeof ApiPublicCompanyReviewRoute
  '/api/public/confirm': typeof ApiPublicConfirmRoute
  '/api/public/coupon': typeof ApiPublicCouponRoute
  '/api/public/deposit': typeof ApiPublicDepositRoute
  '/api/public/review': typeof ApiPublicReviewRoute
  '/api/public/staff': typeof ApiPublicStaffRoute
  '/b/$slug/entrar': typeof BSlugEntrarRoute
  '/b/$slug/minha-conta': typeof BSlugMinhaContaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/b/$slug': typeof BSlugIndexRoute
  '/api/public/hooks/confirmations': typeof ApiPublicHooksConfirmationsRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/hooks/review-invites': typeof ApiPublicHooksReviewInvitesRoute
  '/b/$slug/avaliar/$appointmentId': typeof BSlugAvaliarAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/no-access': typeof AuthenticatedNoAccessRoute
  '/avaliacao/$token': typeof AvaliacaoTokenRoute
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/niches': typeof AuthenticatedAdminNichesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/attendance': typeof AuthenticatedAppAttendanceRoute
  '/_authenticated/app/birthdays': typeof AuthenticatedAppBirthdaysRoute
  '/_authenticated/app/blocks': typeof AuthenticatedAppBlocksRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/commissions': typeof AuthenticatedAppCommissionsRoute
  '/_authenticated/app/confirmations': typeof AuthenticatedAppConfirmationsRoute
  '/_authenticated/app/coupons': typeof AuthenticatedAppCouponsRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/app/finances': typeof AuthenticatedAppFinancesRoute
  '/_authenticated/app/gallery': typeof AuthenticatedAppGalleryRoute
  '/_authenticated/app/link': typeof AuthenticatedAppLinkRoute
  '/_authenticated/app/loyalty': typeof AuthenticatedAppLoyaltyRoute
  '/_authenticated/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/_authenticated/app/plans': typeof AuthenticatedAppPlansRoute
  '/_authenticated/app/portal': typeof AuthenticatedAppPortalRoute
  '/_authenticated/app/procedures': typeof AuthenticatedAppProceduresRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/_authenticated/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/_authenticated/app/sales': typeof AuthenticatedAppSalesRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/staff': typeof AuthenticatedAppStaffRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/public/anamnesis': typeof ApiPublicAnamnesisRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/api/public/company-review': typeof ApiPublicCompanyReviewRoute
  '/api/public/confirm': typeof ApiPublicConfirmRoute
  '/api/public/coupon': typeof ApiPublicCouponRoute
  '/api/public/deposit': typeof ApiPublicDepositRoute
  '/api/public/review': typeof ApiPublicReviewRoute
  '/api/public/staff': typeof ApiPublicStaffRoute
  '/b/$slug/entrar': typeof BSlugEntrarRoute
  '/b/$slug/minha-conta': typeof BSlugMinhaContaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/api/public/hooks/confirmations': typeof ApiPublicHooksConfirmationsRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/hooks/review-invites': typeof ApiPublicHooksReviewInvitesRoute
  '/b/$slug/avaliar/$appointmentId': typeof BSlugAvaliarAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/marketplace'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/app'
    | '/change-password'
    | '/home'
    | '/no-access'
    | '/avaliacao/$token'
    | '/avaliar/$token'
    | '/confirmar/$token'
    | '/admin/companies'
    | '/admin/logs'
    | '/admin/niches'
    | '/admin/payments'
    | '/admin/settings'
    | '/app/agenda'
    | '/app/ai'
    | '/app/attendance'
    | '/app/birthdays'
    | '/app/blocks'
    | '/app/campaigns'
    | '/app/commissions'
    | '/app/confirmations'
    | '/app/coupons'
    | '/app/customers'
    | '/app/finances'
    | '/app/gallery'
    | '/app/link'
    | '/app/loyalty'
    | '/app/payments'
    | '/app/plans'
    | '/app/portal'
    | '/app/procedures'
    | '/app/products'
    | '/app/reports'
    | '/app/reviews'
    | '/app/rewards'
    | '/app/sales'
    | '/app/services'
    | '/app/settings'
    | '/app/staff'
    | '/app/users'
    | '/app/whatsapp'
    | '/api/public/anamnesis'
    | '/api/public/book'
    | '/api/public/company-review'
    | '/api/public/confirm'
    | '/api/public/coupon'
    | '/api/public/deposit'
    | '/api/public/review'
    | '/api/public/staff'
    | '/b/$slug/entrar'
    | '/b/$slug/minha-conta'
    | '/admin/'
    | '/app/'
    | '/b/$slug/'
    | '/api/public/hooks/confirmations'
    | '/api/public/hooks/reminders'
    | '/api/public/hooks/review-invites'
    | '/b/$slug/avaliar/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/marketplace'
    | '/reset-password'
    | '/termos'
    | '/change-password'
    | '/home'
    | '/no-access'
    | '/avaliacao/$token'
    | '/avaliar/$token'
    | '/confirmar/$token'
    | '/admin/companies'
    | '/admin/logs'
    | '/admin/niches'
    | '/admin/payments'
    | '/admin/settings'
    | '/app/agenda'
    | '/app/ai'
    | '/app/attendance'
    | '/app/birthdays'
    | '/app/blocks'
    | '/app/campaigns'
    | '/app/commissions'
    | '/app/confirmations'
    | '/app/coupons'
    | '/app/customers'
    | '/app/finances'
    | '/app/gallery'
    | '/app/link'
    | '/app/loyalty'
    | '/app/payments'
    | '/app/plans'
    | '/app/portal'
    | '/app/procedures'
    | '/app/products'
    | '/app/reports'
    | '/app/reviews'
    | '/app/rewards'
    | '/app/sales'
    | '/app/services'
    | '/app/settings'
    | '/app/staff'
    | '/app/users'
    | '/app/whatsapp'
    | '/api/public/anamnesis'
    | '/api/public/book'
    | '/api/public/company-review'
    | '/api/public/confirm'
    | '/api/public/coupon'
    | '/api/public/deposit'
    | '/api/public/review'
    | '/api/public/staff'
    | '/b/$slug/entrar'
    | '/b/$slug/minha-conta'
    | '/admin'
    | '/app'
    | '/b/$slug'
    | '/api/public/hooks/confirmations'
    | '/api/public/hooks/reminders'
    | '/api/public/hooks/review-invites'
    | '/b/$slug/avaliar/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/marketplace'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/change-password'
    | '/_authenticated/home'
    | '/_authenticated/no-access'
    | '/avaliacao/$token'
    | '/avaliar/$token'
    | '/confirmar/$token'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/niches'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/attendance'
    | '/_authenticated/app/birthdays'
    | '/_authenticated/app/blocks'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/commissions'
    | '/_authenticated/app/confirmations'
    | '/_authenticated/app/coupons'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/finances'
    | '/_authenticated/app/gallery'
    | '/_authenticated/app/link'
    | '/_authenticated/app/loyalty'
    | '/_authenticated/app/payments'
    | '/_authenticated/app/plans'
    | '/_authenticated/app/portal'
    | '/_authenticated/app/procedures'
    | '/_authenticated/app/products'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/reviews'
    | '/_authenticated/app/rewards'
    | '/_authenticated/app/sales'
    | '/_authenticated/app/services'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/staff'
    | '/_authenticated/app/users'
    | '/_authenticated/app/whatsapp'
    | '/api/public/anamnesis'
    | '/api/public/book'
    | '/api/public/company-review'
    | '/api/public/confirm'
    | '/api/public/coupon'
    | '/api/public/deposit'
    | '/api/public/review'
    | '/api/public/staff'
    | '/b/$slug/entrar'
    | '/b/$slug/minha-conta'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/b/$slug/'
    | '/api/public/hooks/confirmations'
    | '/api/public/hooks/reminders'
    | '/api/public/hooks/review-invites'
    | '/b/$slug/avaliar/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  AvaliacaoTokenRoute: typeof AvaliacaoTokenRoute
  AvaliarTokenRoute: typeof AvaliarTokenRoute
  ConfirmarTokenRoute: typeof ConfirmarTokenRoute
  ApiPublicAnamnesisRoute: typeof ApiPublicAnamnesisRoute
  ApiPublicBookRoute: typeof ApiPublicBookRoute
  ApiPublicCompanyReviewRoute: typeof ApiPublicCompanyReviewRoute
  ApiPublicConfirmRoute: typeof ApiPublicConfirmRoute
  ApiPublicCouponRoute: typeof ApiPublicCouponRoute
  ApiPublicDepositRoute: typeof ApiPublicDepositRoute
  ApiPublicReviewRoute: typeof ApiPublicReviewRoute
  ApiPublicStaffRoute: typeof ApiPublicStaffRoute
  BSlugEntrarRoute: typeof BSlugEntrarRoute
  BSlugMinhaContaRoute: typeof BSlugMinhaContaRoute
  BSlugIndexRoute: typeof BSlugIndexRoute
  ApiPublicHooksConfirmationsRoute: typeof ApiPublicHooksConfirmationsRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
  ApiPublicHooksReviewInvitesRoute: typeof ApiPublicHooksReviewInvitesRoute
  BSlugAvaliarAppointmentIdRoute: typeof BSlugAvaliarAppointmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar/$token': {
      id: '/confirmar/$token'
      path: '/confirmar/$token'
      fullPath: '/confirmar/$token'
      preLoaderRoute: typeof ConfirmarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar/$token': {
      id: '/avaliar/$token'
      path: '/avaliar/$token'
      fullPath: '/avaliar/$token'
      preLoaderRoute: typeof AvaliarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao/$token': {
      id: '/avaliacao/$token'
      path: '/avaliacao/$token'
      fullPath: '/avaliacao/$token'
      preLoaderRoute: typeof AvaliacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/no-access': {
      id: '/_authenticated/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof AuthenticatedNoAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/b/$slug/': {
      id: '/b/$slug/'
      path: '/b/$slug'
      fullPath: '/b/$slug/'
      preLoaderRoute: typeof BSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/b/$slug/minha-conta': {
      id: '/b/$slug/minha-conta'
      path: '/b/$slug/minha-conta'
      fullPath: '/b/$slug/minha-conta'
      preLoaderRoute: typeof BSlugMinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/entrar': {
      id: '/b/$slug/entrar'
      path: '/b/$slug/entrar'
      fullPath: '/b/$slug/entrar'
      preLoaderRoute: typeof BSlugEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff': {
      id: '/api/public/staff'
      path: '/api/public/staff'
      fullPath: '/api/public/staff'
      preLoaderRoute: typeof ApiPublicStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/review': {
      id: '/api/public/review'
      path: '/api/public/review'
      fullPath: '/api/public/review'
      preLoaderRoute: typeof ApiPublicReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deposit': {
      id: '/api/public/deposit'
      path: '/api/public/deposit'
      fullPath: '/api/public/deposit'
      preLoaderRoute: typeof ApiPublicDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/coupon': {
      id: '/api/public/coupon'
      path: '/api/public/coupon'
      fullPath: '/api/public/coupon'
      preLoaderRoute: typeof ApiPublicCouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/confirm': {
      id: '/api/public/confirm'
      path: '/api/public/confirm'
      fullPath: '/api/public/confirm'
      preLoaderRoute: typeof ApiPublicConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/company-review': {
      id: '/api/public/company-review'
      path: '/api/public/company-review'
      fullPath: '/api/public/company-review'
      preLoaderRoute: typeof ApiPublicCompanyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book': {
      id: '/api/public/book'
      path: '/api/public/book'
      fullPath: '/api/public/book'
      preLoaderRoute: typeof ApiPublicBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anamnesis': {
      id: '/api/public/anamnesis'
      path: '/api/public/anamnesis'
      fullPath: '/api/public/anamnesis'
      preLoaderRoute: typeof ApiPublicAnamnesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/whatsapp': {
      id: '/_authenticated/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AuthenticatedAppWhatsappRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/staff': {
      id: '/_authenticated/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AuthenticatedAppStaffRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/sales': {
      id: '/_authenticated/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AuthenticatedAppSalesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/rewards': {
      id: '/_authenticated/app/rewards'
      path: '/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AuthenticatedAppRewardsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reviews': {
      id: '/_authenticated/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AuthenticatedAppReviewsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/procedures': {
      id: '/_authenticated/app/procedures'
      path: '/procedures'
      fullPath: '/app/procedures'
      preLoaderRoute: typeof AuthenticatedAppProceduresRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/portal': {
      id: '/_authenticated/app/portal'
      path: '/portal'
      fullPath: '/app/portal'
      preLoaderRoute: typeof AuthenticatedAppPortalRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/plans': {
      id: '/_authenticated/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AuthenticatedAppPlansRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/payments': {
      id: '/_authenticated/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AuthenticatedAppPaymentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/loyalty': {
      id: '/_authenticated/app/loyalty'
      path: '/loyalty'
      fullPath: '/app/loyalty'
      preLoaderRoute: typeof AuthenticatedAppLoyaltyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/link': {
      id: '/_authenticated/app/link'
      path: '/link'
      fullPath: '/app/link'
      preLoaderRoute: typeof AuthenticatedAppLinkRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/gallery': {
      id: '/_authenticated/app/gallery'
      path: '/gallery'
      fullPath: '/app/gallery'
      preLoaderRoute: typeof AuthenticatedAppGalleryRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/finances': {
      id: '/_authenticated/app/finances'
      path: '/finances'
      fullPath: '/app/finances'
      preLoaderRoute: typeof AuthenticatedAppFinancesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/coupons': {
      id: '/_authenticated/app/coupons'
      path: '/coupons'
      fullPath: '/app/coupons'
      preLoaderRoute: typeof AuthenticatedAppCouponsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/confirmations': {
      id: '/_authenticated/app/confirmations'
      path: '/confirmations'
      fullPath: '/app/confirmations'
      preLoaderRoute: typeof AuthenticatedAppConfirmationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/commissions': {
      id: '/_authenticated/app/commissions'
      path: '/commissions'
      fullPath: '/app/commissions'
      preLoaderRoute: typeof AuthenticatedAppCommissionsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/blocks': {
      id: '/_authenticated/app/blocks'
      path: '/blocks'
      fullPath: '/app/blocks'
      preLoaderRoute: typeof AuthenticatedAppBlocksRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/birthdays': {
      id: '/_authenticated/app/birthdays'
      path: '/birthdays'
      fullPath: '/app/birthdays'
      preLoaderRoute: typeof AuthenticatedAppBirthdaysRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/attendance': {
      id: '/_authenticated/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AuthenticatedAppAttendanceRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/niches': {
      id: '/_authenticated/admin/niches'
      path: '/niches'
      fullPath: '/admin/niches'
      preLoaderRoute: typeof AuthenticatedAdminNichesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/b/$slug/avaliar/$appointmentId': {
      id: '/b/$slug/avaliar/$appointmentId'
      path: '/b/$slug/avaliar/$appointmentId'
      fullPath: '/b/$slug/avaliar/$appointmentId'
      preLoaderRoute: typeof BSlugAvaliarAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/review-invites': {
      id: '/api/public/hooks/review-invites'
      path: '/api/public/hooks/review-invites'
      fullPath: '/api/public/hooks/review-invites'
      preLoaderRoute: typeof ApiPublicHooksReviewInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/confirmations': {
      id: '/api/public/hooks/confirmations'
      path: '/api/public/hooks/confirmations'
      fullPath: '/api/public/hooks/confirmations'
      preLoaderRoute: typeof ApiPublicHooksConfirmationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminNichesRoute: typeof AuthenticatedAdminNichesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminNichesRoute: AuthenticatedAdminNichesRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppAttendanceRoute: typeof AuthenticatedAppAttendanceRoute
  AuthenticatedAppBirthdaysRoute: typeof AuthenticatedAppBirthdaysRoute
  AuthenticatedAppBlocksRoute: typeof AuthenticatedAppBlocksRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppCommissionsRoute: typeof AuthenticatedAppCommissionsRoute
  AuthenticatedAppConfirmationsRoute: typeof AuthenticatedAppConfirmationsRoute
  AuthenticatedAppCouponsRoute: typeof AuthenticatedAppCouponsRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppFinancesRoute: typeof AuthenticatedAppFinancesRoute
  AuthenticatedAppGalleryRoute: typeof AuthenticatedAppGalleryRoute
  AuthenticatedAppLinkRoute: typeof AuthenticatedAppLinkRoute
  AuthenticatedAppLoyaltyRoute: typeof AuthenticatedAppLoyaltyRoute
  AuthenticatedAppPaymentsRoute: typeof AuthenticatedAppPaymentsRoute
  AuthenticatedAppPlansRoute: typeof AuthenticatedAppPlansRoute
  AuthenticatedAppPortalRoute: typeof AuthenticatedAppPortalRoute
  AuthenticatedAppProceduresRoute: typeof AuthenticatedAppProceduresRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppReviewsRoute: typeof AuthenticatedAppReviewsRoute
  AuthenticatedAppRewardsRoute: typeof AuthenticatedAppRewardsRoute
  AuthenticatedAppSalesRoute: typeof AuthenticatedAppSalesRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStaffRoute: typeof AuthenticatedAppStaffRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppWhatsappRoute: typeof AuthenticatedAppWhatsappRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppAttendanceRoute: AuthenticatedAppAttendanceRoute,
  AuthenticatedAppBirthdaysRoute: AuthenticatedAppBirthdaysRoute,
  AuthenticatedAppBlocksRoute: AuthenticatedAppBlocksRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppCommissionsRoute: AuthenticatedAppCommissionsRoute,
  AuthenticatedAppConfirmationsRoute: AuthenticatedAppConfirmationsRoute,
  AuthenticatedAppCouponsRoute: AuthenticatedAppCouponsRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppFinancesRoute: AuthenticatedAppFinancesRoute,
  AuthenticatedAppGalleryRoute: AuthenticatedAppGalleryRoute,
  AuthenticatedAppLinkRoute: AuthenticatedAppLinkRoute,
  AuthenticatedAppLoyaltyRoute: AuthenticatedAppLoyaltyRoute,
  AuthenticatedAppPaymentsRoute: AuthenticatedAppPaymentsRoute,
  AuthenticatedAppPlansRoute: AuthenticatedAppPlansRoute,
  AuthenticatedAppPortalRoute: AuthenticatedAppPortalRoute,
  AuthenticatedAppProceduresRoute: AuthenticatedAppProceduresRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppReviewsRoute: AuthenticatedAppReviewsRoute,
  AuthenticatedAppRewardsRoute: AuthenticatedAppRewardsRoute,
  AuthenticatedAppSalesRoute: AuthenticatedAppSalesRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStaffRoute: AuthenticatedAppStaffRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppWhatsappRoute: AuthenticatedAppWhatsappRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNoAccessRoute: typeof AuthenticatedNoAccessRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNoAccessRoute: AuthenticatedNoAccessRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MarketplaceRoute: MarketplaceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  AvaliacaoTokenRoute: AvaliacaoTokenRoute,
  AvaliarTokenRoute: AvaliarTokenRoute,
  ConfirmarTokenRoute: ConfirmarTokenRoute,
  ApiPublicAnamnesisRoute: ApiPublicAnamnesisRoute,
  ApiPublicBookRoute: ApiPublicBookRoute,
  ApiPublicCompanyReviewRoute: ApiPublicCompanyReviewRoute,
  ApiPublicConfirmRoute: ApiPublicConfirmRoute,
  ApiPublicCouponRoute: ApiPublicCouponRoute,
  ApiPublicDepositRoute: ApiPublicDepositRoute,
  ApiPublicReviewRoute: ApiPublicReviewRoute,
  ApiPublicStaffRoute: ApiPublicStaffRoute,
  BSlugEntrarRoute: BSlugEntrarRoute,
  BSlugMinhaContaRoute: BSlugMinhaContaRoute,
  BSlugIndexRoute: BSlugIndexRoute,
  ApiPublicHooksConfirmationsRoute: ApiPublicHooksConfirmationsRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
  ApiPublicHooksReviewInvitesRoute: ApiPublicHooksReviewInvitesRoute,
  BSlugAvaliarAppointmentIdRoute: BSlugAvaliarAppointmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
