/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthenticatedNoAccessRouteImport } from './routes/_authenticated/no-access'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicBookRouteImport } from './routes/api/public/book'
import { Route as AuthenticatedAppStaffRouteImport } from './routes/_authenticated/app/staff'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app/services'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app/reports'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app/products'
import { Route as AuthenticatedAppFinancesRouteImport } from './routes/_authenticated/app/finances'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app/customers'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app/agenda'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminNichesRouteImport } from './routes/_authenticated/admin/niches'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNoAccessRoute = AuthenticatedNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicBookRoute = ApiPublicBookRouteImport.update({
  id: '/api/public/book',
  path: '/api/public/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppStaffRoute = AuthenticatedAppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFinancesRoute =
  AuthenticatedAppFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNichesRoute =
  AuthenticatedAdminNichesRouteImport.update({
    id: '/niches',
    path: '/niches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/no-access': typeof AuthenticatedNoAccessRoute
  '/b/$slug': typeof BSlugRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/niches': typeof AuthenticatedAdminNichesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/finances': typeof AuthenticatedAppFinancesRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/staff': typeof AuthenticatedAppStaffRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/no-access': typeof AuthenticatedNoAccessRoute
  '/b/$slug': typeof BSlugRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/niches': typeof AuthenticatedAdminNichesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/finances': typeof AuthenticatedAppFinancesRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/staff': typeof AuthenticatedAppStaffRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/no-access': typeof AuthenticatedNoAccessRoute
  '/b/$slug': typeof BSlugRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/niches': typeof AuthenticatedAdminNichesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/app/finances': typeof AuthenticatedAppFinancesRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/staff': typeof AuthenticatedAppStaffRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/home'
    | '/no-access'
    | '/b/$slug'
    | '/admin/companies'
    | '/admin/niches'
    | '/admin/payments'
    | '/admin/settings'
    | '/app/agenda'
    | '/app/customers'
    | '/app/finances'
    | '/app/products'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/staff'
    | '/api/public/book'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/no-access'
    | '/b/$slug'
    | '/admin/companies'
    | '/admin/niches'
    | '/admin/payments'
    | '/admin/settings'
    | '/app/agenda'
    | '/app/customers'
    | '/app/finances'
    | '/app/products'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/staff'
    | '/api/public/book'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/home'
    | '/_authenticated/no-access'
    | '/b/$slug'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/niches'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/finances'
    | '/_authenticated/app/products'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/services'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/staff'
    | '/api/public/book'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BSlugRoute: typeof BSlugRoute
  ApiPublicBookRoute: typeof ApiPublicBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/no-access': {
      id: '/_authenticated/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof AuthenticatedNoAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/book': {
      id: '/api/public/book'
      path: '/api/public/book'
      fullPath: '/api/public/book'
      preLoaderRoute: typeof ApiPublicBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/staff': {
      id: '/_authenticated/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AuthenticatedAppStaffRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/finances': {
      id: '/_authenticated/app/finances'
      path: '/finances'
      fullPath: '/app/finances'
      preLoaderRoute: typeof AuthenticatedAppFinancesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/niches': {
      id: '/_authenticated/admin/niches'
      path: '/niches'
      fullPath: '/admin/niches'
      preLoaderRoute: typeof AuthenticatedAdminNichesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminNichesRoute: typeof AuthenticatedAdminNichesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
    AuthenticatedAdminNichesRoute: AuthenticatedAdminNichesRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppFinancesRoute: typeof AuthenticatedAppFinancesRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStaffRoute: typeof AuthenticatedAppStaffRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppFinancesRoute: AuthenticatedAppFinancesRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStaffRoute: AuthenticatedAppStaffRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNoAccessRoute: typeof AuthenticatedNoAccessRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNoAccessRoute: AuthenticatedNoAccessRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BSlugRoute: BSlugRoute,
  ApiPublicBookRoute: ApiPublicBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
